# vim: et sw=2 ts=2
---
image: harbor.infra.run/infra.run/builder:latest

stages:
  - build

build:
  stage: build
  script: docker_build_and_push.sh -s "harbor.infra.run/infra.run/b3scale-operator"
  except:
    - main

build-tag:
  stage: build
  script: docker_build_and_push.sh -l -s "harbor.infra.run/infra.run/b3scale-operator"
  only:
    - main
