apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bbbfrontends.b3scale.infra.run
spec:
  group: b3scale.infra.run
  names:
    kind: BBBFrontend
    listKind: BBBFrontendList
    plural: bbbfrontends
    singular: bbbfrontend
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                settings:
                  type: object
                  properties:
                    required_tags:
                      type: array
                      nullable: true
                      items:
                        type: string
                    default_presentation:
                      type: object
                      nullable: true
                      properties:
                        url:
                          type: string
                        force:
                          type: boolean

