apiVersion: v1
kind: ServiceAccount
metadata:
  name: b3scale-operator
  namespace: b3scale-operator

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: b3scale-operator
  namespace: b3scale-operator
rules:
  - apiGroups: [ "b3scale.infra.run" ]
    resources: [ "bbbfrontends" ]
    verbs: [ "get", "watch", "list", "update" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get", "watch", "list", "update", "delete", "create" ]
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get", "watch", "list", "update", "delete", "create" ]


---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: b3scale-operator
  namespace: b3scale-operator
subjects:
  - kind: ServiceAccount
    name: b3scale-operator
    namespace: b3scale-operator
roleRef:
  kind: ClusterRole
  name: b3scale-operator
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: b3scale-operator
  namespace: b3scale-operator
  labels:
    app.kubernetes.io/name: b3scale-operator
    app.kubernetes.io/instance: b3scale-operator

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: b3scale-operator
      app.kubernetes.io/instance: b3scale-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: b3scale-operator
        app.kubernetes.io/instance: b3scale-operator
    spec:
      serviceAccountName: b3scale-operator
      containers:
        - name: b3scale-operator
          image: "harbor.infra.run/infra.run/b3scale-operator:latest"
          volumeMounts:
            - mountPath: "/app/b3scale-operator-config.yaml"
              name: b3scale-operator-config
      volumes:
        - name: b3scale-operator-config
          secret:
            secretName: b3scale-operator-config

---

apiVersion: v1
kind: Secret
metadata:
  name: b3scale-operator-config
type: Opaque
stringData:
  b3scale-operator-config.yaml: |
    b3Scale:
      host: "bbb.bastelgenosse.de"
      accessToken: ""
    
    kubernetes:
      inCluster:
        dummyValue: true
