apiVersion: v1
kind: Secret
metadata:
  name: testeroni
  namespace: b3scale-operator
stringData:
  FOO: "UuBie5boohua0xeewei4lei0eu9shahC"

---

apiVersion: b3scale.io/v1
kind: BBBFrontend
metadata:
  name: frontend-provided-credentials
  namespace: b3scale-operator
spec:
  credentials:
    frontend: "das-ist-ein-frontend"
    secretRef:
      name: testeroni
      key: "FOO"
  settings:
    requiredTags:
      - "bbb_24_mediasoup"

---

apiVersion: b3scale.io/v1
kind: BBBFrontend
metadata:
  name: frontend-generate-credentials
  namespace: b3scale-operator
spec:
  settings:
    requiredTags:
      - "bbb_24_mediasoup"
