name: Remove Container Image from GHCR on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  delete-image:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete container image
      run: |
        docker image rm -f ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:pr-${{ github.event.pull_request.number }}

